import type {
  HotelRoomDailyInventory,
  HotelRoomType,
  PlatformData,
  ServiceProduct,
} from "@travel/domain";
import { createOrderProductSnapshot } from "@travel/domain";

const sanyaProduct: ServiceProduct = {
  id: "product-sanya",
  name: "三亚海棠湾滨海疗养5日",
  type: "travel",
  summary: "面向集团员工的海滨休养服务，可按实际需求协调交通与住宿。",
  coverImage: "/images/products/coastal-cliff.png",
  gallery: [
    {
      imageUrl: "/images/products/coastal-cliff.png",
      description: "海棠湾滨海环境开阔，适合安排轻松的海边休养时光。",
    },
    {
      imageUrl: "/images/products/garden-retreat.png",
      description: "园林式休憩空间，方便员工在疗养期间散步放松。",
    },
  ],
  quotaReference: { min: 3000, max: 5000 },
  serviceDescription: "提供住宿协调、往返交通建议和接送站等可选服务。",
  notes: "具体安排以工作人员线下沟通确认结果为准。",
  visibility: {
    scope: "specified_groups",
    groupIds: ["group-xingchen"],
  },
  status: "published",
  sortOrder: 10,
  recommended: true,
  linkedHotelProductIds: ["product-hotel-sanya-bay"],
  travelDetails: {
    destination: "海南·三亚",
    destinationHighlights: "气候温暖，滨海环境适合放松休养。",
    suitableTravelMonths: [10, 11, 12, 1, 2, 3, 4],
    recommendedStayDays: "4-6天",
    transportOptions: ["飞机", "高铁"],
    accommodation: "海棠湾合作酒店，具体房型按订单确认。",
    dining: "可协助安排酒店早餐和当地特色餐饮。",
    pickupService: "可选接送机服务。",
    serviceScope: "包含住宿协调与基础服务，不包含员工自由活动费用。",
  },
  createdAt: "2026-06-01T09:00:00+08:00",
  updatedAt: "2026-06-18T14:30:00+08:00",
};

const sanyaHotelProduct: ServiceProduct = {
  id: "product-hotel-sanya-bay",
  name: "三亚海棠湾康养酒店",
  type: "hotel",
  summary: "海棠湾合作酒店，可单独预订，也可作为三亚疗养产品住宿选择。",
  coverImage: "/mock-images/hotel-sanya-cover.jpg",
  gallery: [
    {
      imageUrl: "/images/products/garden-retreat.png",
      description: "酒店园林与休憩空间环境舒适，适合疗养期间散步放松。",
    },
    {
      imageUrl: "/images/products/lake-retreat.png",
      description: "酒店周边环境安静开阔，可根据实际安排体验休闲设施。",
    },
  ],
  quotaReference: { min: 800, max: 1280 },
  serviceDescription: "提供住宿预订协调、早餐和基础入住支持。",
  notes: "房态和价格以后台维护日期库存为准。",
  visibility: {
    scope: "specified_groups",
    groupIds: ["group-xingchen"],
  },
  status: "published",
  sortOrder: 11,
  recommended: false,
  hotelDetails: {
    city: "海南·三亚",
    address: "三亚市海棠湾合作酒店片区",
    starRating: "高端度假酒店",
    facilities: "泳池、早餐厅、健身房、康养活动室",
    trafficInfo: "距离三亚凤凰机场约45分钟车程",
    checkInPolicy: "入住时间14:00后，离店时间12:00前",
    paidServices: [
      {
        title: "接送服务",
        description:
          "可协助协调机场、车站或酒店周边接送，费用根据时间、人数、车型和距离另行确认。",
      },
    ],
  },
  createdAt: "2026-06-01T09:10:00+08:00",
  updatedAt: "2026-06-18T14:30:00+08:00",
};

const mogaMountainProduct: ServiceProduct = {
  id: "product-moganshan",
  name: "莫干山竹海静养4日",
  type: "travel",
  summary: "山林环境中的短期静养服务。",
  coverImage: "/images/products/mountain-retreat.png",
  quotaReference: { min: 2000, max: 3500 },
  serviceDescription: "提供住宿协调、当地交通建议及基础行程支持。",
  notes: "适宜时间和房态需由工作人员二次确认。",
  visibility: { scope: "all_groups" },
  status: "published",
  sortOrder: 20,
  recommended: true,
  travelDetails: {
    destination: "浙江·莫干山",
    destinationHighlights: "山林环境安静，适合短期休养。",
    suitableTravelMonths: [4, 5, 6, 7, 8, 9, 10, 11],
    recommendedStayDays: "3-5天",
    transportOptions: ["高铁", "汽车"],
    accommodation: "合作民宿或度假酒店。",
    dining: "可协助安排当地餐饮。",
    pickupService: "可选接送站服务。",
    serviceScope: "包含住宿与接送协调，不包含员工个人消费。",
  },
  createdAt: "2026-06-03T09:00:00+08:00",
  updatedAt: "2026-06-20T10:00:00+08:00",
};

const draftProduct: ServiceProduct = {
  id: "product-dali-draft",
  name: "大理慢生活疗养服务",
  type: "travel",
  summary: "待完善的内部商品草稿。",
  coverImage: "/mock-images/dali-cover.jpg",
  serviceDescription: "待补充。",
  notes: "未上架，仅后台可见。",
  visibility: { scope: "all_groups" },
  status: "draft",
  travelDetails: {
    destination: "云南·大理",
    destinationHighlights: "气候舒适，适合慢节奏休养。",
    suitableTravelMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    recommendedStayDays: "5-7天",
    serviceScope: "待补充。",
  },
  createdAt: "2026-06-22T09:00:00+08:00",
  updatedAt: "2026-06-22T09:00:00+08:00",
};

const lakeProduct: ServiceProduct = {
  id: "product-qiandaohu",
  name: "千岛湖湖畔舒心疗养4日",
  type: "travel",
  summary: "临湖而居，在开阔水景与舒缓节奏中放松身心。",
  coverImage: "/images/products/lake-retreat.png",
  quotaReference: { min: 3600, max: 4800 },
  serviceDescription: "提供湖景住宿、基础行程协调和接送站服务。",
  notes: "具体房型和出行安排以工作人员确认结果为准。",
  visibility: { scope: "all_groups" },
  status: "published",
  sortOrder: 30,
  recommended: true,
  travelDetails: {
    destination: "浙江·千岛湖",
    destinationHighlights: "湖光开阔、环境安静，适合短期舒心休养。",
    suitableTravelMonths: [3, 4, 5, 6, 9, 10, 11],
    recommendedStayDays: "4天3晚",
    transportOptions: ["高铁", "汽车"],
    accommodation: "合作湖景度假酒店。",
    pickupService: "可选高铁站接送。",
    serviceScope: "包含住宿与基础行程协调，不包含个人自由消费。",
  },
  createdAt: "2026-06-24T09:00:00+08:00",
  updatedAt: "2026-06-24T09:00:00+08:00",
};

const ancientTownProduct: ServiceProduct = {
  id: "product-ancient-town",
  name: "江南水乡古镇慢养4日",
  type: "travel",
  summary: "漫步水乡古镇，以轻行程体验江南人文与慢生活。",
  coverImage: "/images/products/ancient-town.png",
  quotaReference: { min: 2800, max: 4000 },
  serviceDescription: "提供古镇住宿、文化体验与当地交通协调。",
  notes: "节假日期间房态和行程需提前确认。",
  visibility: { scope: "all_groups" },
  status: "published",
  sortOrder: 40,
  recommended: false,
  travelDetails: {
    destination: "浙江·江南古镇",
    destinationHighlights: "水乡街巷节奏舒缓，适合人文漫游与轻度休养。",
    suitableTravelMonths: [3, 4, 5, 9, 10, 11],
    recommendedStayDays: "4天3晚",
    transportOptions: ["高铁", "汽车"],
    accommodation: "古镇合作精品酒店。",
    serviceScope: "包含住宿和基础活动协调，不包含个人购物消费。",
  },
  createdAt: "2026-06-24T09:10:00+08:00",
  updatedAt: "2026-06-24T09:10:00+08:00",
};

const canyonProduct: ServiceProduct = {
  id: "product-enshi-canyon",
  name: "恩施大峡谷森林康养5日",
  type: "travel",
  summary: "深入峡谷与森林，在清新自然环境中进行轻户外休养。",
  coverImage: "/images/products/canyon-retreat.png",
  quotaReference: { min: 4200, max: 5600 },
  serviceDescription: "提供住宿、景区交通建议及轻量行程协调。",
  notes: "部分行程包含步行，请根据个人身体情况选择。",
  visibility: { scope: "all_groups" },
  status: "published",
  sortOrder: 50,
  recommended: false,
  travelDetails: {
    destination: "湖北·恩施",
    destinationHighlights: "峡谷与森林资源丰富，空气清新，适合自然康养。",
    suitableTravelMonths: [4, 5, 6, 7, 8, 9, 10],
    recommendedStayDays: "5天4晚",
    transportOptions: ["飞机", "高铁"],
    accommodation: "景区周边合作度假酒店。",
    serviceScope: "包含住宿和基础行程协调，不包含个人自选项目。",
  },
  createdAt: "2026-06-24T09:20:00+08:00",
  updatedAt: "2026-06-24T09:20:00+08:00",
};

const gardenProduct: ServiceProduct = {
  id: "product-suzhou-garden",
  name: "苏州园林雅韵静养3日",
  type: "travel",
  summary: "在园林与水巷之间感受雅致人文，安排轻松短途静养。",
  coverImage: "/images/products/garden-retreat.png",
  quotaReference: { min: 2200, max: 3200 },
  serviceDescription: "提供市区住宿、园林参访和交通协调。",
  notes: "园林参访场次以实际预约结果为准。",
  visibility: { scope: "all_groups" },
  status: "published",
  sortOrder: 60,
  recommended: false,
  travelDetails: {
    destination: "江苏·苏州",
    destinationHighlights: "园林人文浓厚、行程舒缓，适合短途静养。",
    suitableTravelMonths: [3, 4, 5, 9, 10, 11],
    recommendedStayDays: "3天2晚",
    transportOptions: ["高铁", "汽车"],
    accommodation: "苏州市区合作酒店。",
    serviceScope: "包含住宿和基础行程协调，不包含个人餐饮消费。",
  },
  createdAt: "2026-06-24T09:30:00+08:00",
  updatedAt: "2026-06-24T09:30:00+08:00",
};

const hotelRoomTypes: HotelRoomType[] = [
  {
    id: "room-sanya-garden-king",
    hotelProductId: "product-hotel-sanya-bay",
    name: "园景大床房",
    imageUrl: "/images/products/sanya-bay.png",
    bedType: "大床",
    capacity: 2,
    breakfast: "含双早",
    area: "约45平方米",
    description: "适合个人或双人休养入住。",
    status: "published",
    createdAt: "2026-06-01T09:20:00+08:00",
    updatedAt: "2026-06-01T09:20:00+08:00",
  },
  {
    id: "room-sanya-sea-twin",
    hotelProductId: "product-hotel-sanya-bay",
    name: "海景双床房",
    imageUrl: "/images/products/sanya-bay.png",
    bedType: "双床",
    capacity: 2,
    breakfast: "含双早",
    area: "约50平方米",
    status: "published",
    createdAt: "2026-06-01T09:25:00+08:00",
    updatedAt: "2026-06-01T09:25:00+08:00",
  },
];

const hotelRoomDailyInventories: HotelRoomDailyInventory[] = [
  {
    id: "inventory-sanya-garden-2026-07-12",
    roomTypeId: "room-sanya-garden-king",
    date: "2026-07-12",
    quotaPrice: 900,
    totalInventory: 8,
    usedInventory: 1,
    isAvailable: true,
    updatedAt: "2026-06-01T09:30:00+08:00",
  },
  {
    id: "inventory-sanya-garden-2026-07-13",
    roomTypeId: "room-sanya-garden-king",
    date: "2026-07-13",
    quotaPrice: 900,
    totalInventory: 8,
    usedInventory: 1,
    isAvailable: true,
    updatedAt: "2026-06-01T09:30:00+08:00",
  },
  {
    id: "inventory-sanya-garden-2026-07-14",
    roomTypeId: "room-sanya-garden-king",
    date: "2026-07-14",
    quotaPrice: 900,
    totalInventory: 8,
    usedInventory: 1,
    isAvailable: true,
    updatedAt: "2026-06-01T09:30:00+08:00",
  },
  {
    id: "inventory-sanya-garden-2026-07-15",
    roomTypeId: "room-sanya-garden-king",
    date: "2026-07-15",
    quotaPrice: 900,
    totalInventory: 8,
    usedInventory: 1,
    isAvailable: true,
    updatedAt: "2026-06-01T09:30:00+08:00",
  },
  {
    id: "inventory-sanya-garden-2026-07-16",
    roomTypeId: "room-sanya-garden-king",
    date: "2026-07-16",
    quotaPrice: 900,
    totalInventory: 8,
    usedInventory: 1,
    isAvailable: true,
    updatedAt: "2026-06-01T09:30:00+08:00",
  },
  {
    id: "inventory-sanya-garden-2026-07-17",
    roomTypeId: "room-sanya-garden-king",
    date: "2026-07-17",
    quotaPrice: 900,
    totalInventory: 8,
    usedInventory: 1,
    isAvailable: true,
    updatedAt: "2026-06-01T09:30:00+08:00",
  },
  {
    id: "inventory-sanya-garden-2026-07-18",
    roomTypeId: "room-sanya-garden-king",
    date: "2026-07-18",
    quotaPrice: 900,
    totalInventory: 8,
    usedInventory: 1,
    isAvailable: true,
    updatedAt: "2026-06-01T09:30:00+08:00",
  },
];

/**
 * 固定且可复现的第一阶段 Mock 数据。
 *
 * 数据刻意覆盖：
 * - 待跟进意向不扣额度
 * - 意向转待确认订单时不扣额度
 * - 订单确认后扣减额度
 * - 订单取消后部分退回额度
 */
export const mockData: PlatformData = {
  operatorAccounts: [
    {
      id: "operator-leader",
      username: "leader",
      password: "123456",
      displayName: "周然",
      role: "leader",
      status: "active",
      pagePermissions: [
        "groups",
        "employees",
        "quotas",
        "products",
        "hotels",
        "intents",
        "orders",
        "reviews",
        "operator_accounts",
      ],
      createdAt: "2025-12-01T09:00:00+08:00",
      updatedAt: "2025-12-01T09:00:00+08:00",
    },
    {
      id: "operator-staff",
      username: "operator",
      password: "123456",
      displayName: "林溪",
      role: "staff",
      status: "active",
      pagePermissions: ["products", "hotels", "intents", "orders"],
      createdAt: "2025-12-02T09:00:00+08:00",
      updatedAt: "2025-12-02T09:00:00+08:00",
    },
  ],
  groups: [
    {
      id: "group-xingchen",
      name: "星辰科技集团",
      contactName: "张经理",
      contactPhone: "13800001001",
      cooperationStartDate: "2026-01-01",
      status: "active",
      createdAt: "2025-12-15T09:00:00+08:00",
    },
    {
      id: "group-lvzhou",
      name: "绿洲建设集团",
      contactName: "李经理",
      contactPhone: "13800001002",
      cooperationStartDate: "2026-03-01",
      status: "active",
      createdAt: "2026-02-15T09:00:00+08:00",
    },
  ],
  employees: [
    {
      id: "employee-zhang",
      name: "张宁",
      phone: "13900002001",
      password: "123456",
      groupId: "group-xingchen",
      department: "研发中心",
      employeeNumber: "XC-1001",
      status: "active",
      createdAt: "2026-01-05T09:00:00+08:00",
    },
    {
      id: "employee-li",
      name: "李晴",
      phone: "13900002002",
      password: "123456",
      groupId: "group-xingchen",
      department: "市场部",
      employeeNumber: "XC-1002",
      status: "active",
      createdAt: "2026-01-05T09:05:00+08:00",
    },
    {
      id: "employee-wang",
      name: "王川",
      phone: "13900002003",
      password: "123456",
      groupId: "group-lvzhou",
      department: "工程管理部",
      employeeNumber: "LZ-2001",
      status: "active",
      createdAt: "2026-03-03T09:00:00+08:00",
    },
  ],
  quotaAccounts: [
    {
      id: "quota-zhang",
      employeeId: "employee-zhang",
      totalGranted: 5000,
      totalDeducted: 3200,
      totalRefunded: 0,
      totalAdjusted: 0,
      availableBalance: 1800,
      updatedAt: "2026-06-15T16:00:00+08:00",
    },
    {
      id: "quota-li",
      employeeId: "employee-li",
      totalGranted: 6000,
      totalDeducted: 2200,
      totalRefunded: 0,
      totalAdjusted: 0,
      availableBalance: 3800,
      updatedAt: "2026-05-10T14:00:00+08:00",
    },
    {
      id: "quota-wang",
      employeeId: "employee-wang",
      totalGranted: 4000,
      totalDeducted: 2500,
      totalRefunded: 1000,
      totalAdjusted: 0,
      availableBalance: 2500,
      updatedAt: "2026-06-25T11:00:00+08:00",
    },
  ],
  serviceProducts: [
    sanyaProduct,
    sanyaHotelProduct,
    mogaMountainProduct,
    lakeProduct,
    ancientTownProduct,
    canyonProduct,
    gardenProduct,
    draftProduct,
  ],
  hotelRoomTypes,
  hotelRoomDailyInventories,
  personalIntents: [
    {
      id: "intent-zhang-sanya",
      employeeId: "employee-zhang",
      productId: "product-sanya",
      expectedTravelDate: "2026-07-12",
      expectedStayDays: 5,
      companionCount: 1,
      preferredTransport: "飞机",
      needsPickup: true,
      accommodationPreference: "安静楼层",
      convenientContactTime: "工作日18:00后",
      status: "converted_to_order",
      assigneeAccountId: "operator-leader",
      internalNote: "已确认主要需求，转订单继续确认。",
      createdAt: "2026-06-10T09:30:00+08:00",
      updatedAt: "2026-06-12T14:00:00+08:00",
    },
    {
      id: "intent-zhang-moganshan",
      employeeId: "employee-zhang",
      productId: "product-moganshan",
      expectedTravelDate: "2026-09-18",
      expectedStayDays: 4,
      companionCount: 0,
      preferredTransport: "高铁",
      needsPickup: true,
      accommodationPreference: "大床",
      convenientContactTime: "下午（14:00-18:00）",
      status: "pending_follow_up",
      createdAt: "2026-07-02T10:20:00+08:00",
      updatedAt: "2026-07-02T10:20:00+08:00",
    },
    {
      id: "intent-li-moganshan",
      employeeId: "employee-li",
      productId: "product-moganshan",
      expectedTravelDate: "2026-08-08",
      expectedStayDays: 4,
      preferredTransport: "高铁",
      needsPickup: true,
      status: "pending_follow_up",
      createdAt: "2026-06-26T10:20:00+08:00",
      updatedAt: "2026-06-26T10:20:00+08:00",
    },
    {
      id: "intent-wang-moganshan",
      employeeId: "employee-wang",
      productId: "product-moganshan",
      expectedTravelDate: "2026-06-20",
      expectedStayDays: 3,
      preferredTransport: "汽车",
      needsPickup: false,
      status: "converted_to_order",
      assigneeAccountId: "operator-staff",
      createdAt: "2026-06-05T11:00:00+08:00",
      updatedAt: "2026-06-08T15:00:00+08:00",
    },
  ],
  personalOrders: [
    {
      id: "order-zhang-sanya",
      orderNumber: "PO-202606-0001",
      sourceIntentId: "intent-zhang-sanya",
      sourceProductId: "product-sanya",
      employeeId: "employee-zhang",
      groupId: "group-xingchen",
      productSnapshot: createOrderProductSnapshot(sanyaProduct),
      departureDate: "2026-07-15",
      returnDate: "2026-07-19",
      transport: "飞机",
      accommodation: "海棠湾合作酒店园景房",
      hotelAccommodation: {
        hotelProductId: "product-hotel-sanya-bay",
        hotelName: "三亚海棠湾康养酒店",
        roomTypeId: "room-sanya-garden-king",
        roomTypeName: "园景大床房",
        checkInDate: "2026-07-15",
        checkOutDate: "2026-07-19",
        nights: 4,
        quotaPricePerNight: 900,
        totalQuota: 3600,
        address: "三亚市海棠湾合作酒店片区",
      },
      pickupService: "三亚机场接送机",
      servicePlan: "5天住宿、往返交通协调及接送机服务。",
      plannedQuotaDeduction: 3200,
      deductedQuota: 3200,
      refundedQuota: 0,
      finalConsumedQuota: 3200,
      status: "waiting_for_service",
      assigneeAccountId: "operator-leader",
      confirmedAt: "2026-06-15T16:00:00+08:00",
      createdAt: "2026-06-12T14:00:00+08:00",
      updatedAt: "2026-06-15T16:00:00+08:00",
    },
    {
      id: "order-li-moganshan-completed",
      orderNumber: "PO-202605-0001",
      sourceProductId: "product-moganshan",
      employeeId: "employee-li",
      groupId: "group-xingchen",
      productSnapshot: createOrderProductSnapshot(mogaMountainProduct),
      departureDate: "2026-05-18",
      returnDate: "2026-05-21",
      transport: "高铁",
      accommodation: "莫干山合作度假酒店",
      pickupService: "高铁站接送",
      servicePlan: "4天3晚住宿、高铁站接送及当地交通协调。",
      plannedQuotaDeduction: 2200,
      deductedQuota: 2200,
      refundedQuota: 0,
      finalConsumedQuota: 2200,
      status: "completed",
      assigneeAccountId: "operator-staff",
      confirmedAt: "2026-05-10T14:00:00+08:00",
      createdAt: "2026-05-08T10:00:00+08:00",
      updatedAt: "2026-05-22T00:00:00+08:00",
    },
    {
      id: "order-wang-moganshan",
      orderNumber: "PO-202606-0002",
      sourceIntentId: "intent-wang-moganshan",
      sourceProductId: "product-moganshan",
      employeeId: "employee-wang",
      groupId: "group-lvzhou",
      productSnapshot: createOrderProductSnapshot(mogaMountainProduct),
      departureDate: "2026-06-20",
      returnDate: "2026-06-22",
      transport: "汽车",
      accommodation: "莫干山合作民宿",
      servicePlan: "3天住宿及当地交通协调。",
      plannedQuotaDeduction: 2500,
      deductedQuota: 2500,
      refundedQuota: 1000,
      finalConsumedQuota: 1500,
      status: "cancelled",
      assigneeAccountId: "operator-staff",
      internalNote: "员工行程变更，线下确认后部分退回额度。",
      confirmedAt: "2026-06-10T15:30:00+08:00",
      createdAt: "2026-06-08T15:00:00+08:00",
      updatedAt: "2026-06-25T11:00:00+08:00",
    },
  ],
  serviceReviews: [
    {
      id: "review-li-moganshan",
      orderId: "order-li-moganshan-completed",
      employeeId: "employee-li",
      productId: "product-moganshan",
      rating: 5,
      content: "环境很安静，住宿和接送安排都比较顺利，适合短期放松。",
      status: "pending_review",
      submittedAt: "2026-05-23T10:30:00+08:00",
      updatedAt: "2026-05-23T10:30:00+08:00",
    },
  ],
  quotaTransactions: [
    {
      id: "transaction-grant-zhang",
      employeeId: "employee-zhang",
      type: "grant",
      amount: 5000,
      balanceAfter: 5000,
      reason: "2026年度员工疗养额度发放",
      operator: "系统管理员",
      occurredAt: "2026-01-06T10:00:00+08:00",
    },
    {
      id: "transaction-grant-li",
      employeeId: "employee-li",
      type: "grant",
      amount: 6000,
      balanceAfter: 6000,
      reason: "2026年度员工疗养额度发放",
      operator: "系统管理员",
      occurredAt: "2026-01-06T10:05:00+08:00",
    },
    {
      id: "transaction-grant-wang",
      employeeId: "employee-wang",
      type: "grant",
      amount: 4000,
      balanceAfter: 4000,
      reason: "2026年度员工疗养额度发放",
      operator: "系统管理员",
      occurredAt: "2026-03-05T10:00:00+08:00",
    },
    {
      id: "transaction-deduct-li",
      employeeId: "employee-li",
      type: "deduction",
      amount: -2200,
      balanceAfter: 3800,
      relatedOrderId: "order-li-moganshan-completed",
      reason: "个人订单确认扣减",
      operator: "后台运营-林溪",
      occurredAt: "2026-05-10T14:00:00+08:00",
    },
    {
      id: "transaction-deduct-wang",
      employeeId: "employee-wang",
      type: "deduction",
      amount: -2500,
      balanceAfter: 1500,
      relatedOrderId: "order-wang-moganshan",
      reason: "个人订单确认扣减",
      operator: "后台运营-林溪",
      occurredAt: "2026-06-10T15:30:00+08:00",
    },
    {
      id: "transaction-deduct-zhang",
      employeeId: "employee-zhang",
      type: "deduction",
      amount: -3200,
      balanceAfter: 1800,
      relatedOrderId: "order-zhang-sanya",
      reason: "个人订单确认扣减",
      operator: "后台运营-周然",
      occurredAt: "2026-06-15T16:00:00+08:00",
    },
    {
      id: "transaction-refund-wang",
      employeeId: "employee-wang",
      type: "refund",
      amount: 1000,
      balanceAfter: 2500,
      relatedOrderId: "order-wang-moganshan",
      reason: "订单变更，部分服务未使用",
      operator: "后台运营-林溪",
      occurredAt: "2026-06-25T11:00:00+08:00",
    },
  ],
};
